### ISSUE TITLE
我的项目echarts版本升级，找不到模块。import 'echarts/lib/chart/pie';

### ISSUE THREAD

**Issue by zh-h** [evilemon/fullstack#1]
是新版的模块都加了一个路径 `lib` ？
原来旧版的是 `import 'echarts/chart/pie';`

**Comment by evilemon** [comment]
你可以看看node_modules文件夹里面的echarts模块里面的pie具体放在哪里，按照具体位置引入就好
main/js/echarts.wrap.js
